[build]
  command = "astro build"
  publish = "dist"

[[redirects]]
  from = "/.well-known/webfinger"
  to = "https://mstdn.party/.well-known/webfinger?resource=acct:spjpgrd@mstdn.party"
  status = 200
